/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-img-element */
import React from 'react';
import Head from 'next/head';
import Footer from '../../components/Footer';
import Navbar from '../../components/Navbar';
import { getData } from '../../utils/fetchData';
import PDFViewer from '../../components/PDFViewer';
import Button from '../../components/Button';
import { useRouter } from 'next/router';


export default function DetailPage({ detailChapter, dataChapter }) {
  const router = useRouter();
  const handleChapter = (id) => {
    router.push(`/baca/${id}`);
  };

  return (
    <>
      <Head>
        <title>Semina || Detail Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-navy">
        <Navbar />
      </section>
      <div className="container my-5">
        <div className="row">
          <div className="col">
            <PDFViewer detailChapter={detailChapter} />
          </div>
        </div>
      </div>
      <section className="pb-5">
        <div className="container">
          <div className=" row gap-y">
            {dataChapter.map((data, index) => {
              if (detailChapter.komik._id === data.komik._id) {
                return (
                  <div
                    className="col-lg-3 col-md-6 col-12 d-grid my-2"
                    key={index}
                  >
                    <Button
                      variant={'btn-green'}
                      action={() => handleChapter(data._id)}
                    >
                      {data.judul}
                    </Button>
                  </div>
                );
              }
            })}
          </div>
        </div>
      </section>
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  const reqDetailChapter = await getData(`api/v1/chapter/${context.params.id}`);
  const resDetailChapter = reqDetailChapter.data;

  const reqChapter = await getData(`api/v1/chapter`);
  const resChapter = reqChapter.data;

  return {
    props: {
      detailChapter: resDetailChapter,
      dataChapter: resChapter,
      id: context.params.id,
    },
  };
}
