/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-img-element */
import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import Button from '../../components/Button';
import CardEvent from '../../components/CardEvent';
import Footer from '../../components/Footer';
import Navbar from '../../components/Navbar';
import Statistics from '../../components/Statistics';
import Stories from '../../components/Stories';
import { useRouter } from 'next/router';
import { getData } from '../../utils/fetchData';
import moment from 'moment';
import { formatDate } from '../../utils/formatDate';
import Cookies from 'js-cookie';
import { Card, Col, Container, ListGroup, Row } from 'react-bootstrap';

export default function DetailPage({ detailPage, id }) {
  const [data, setData] = useState([]);
  useEffect(() => {
    const fetchData = async () => {
      try {
        const res = await getData('api/v1/komik');

        setData(res.data);
      } catch (err) {}
    };

    fetchData();
  }, []);

  const router = useRouter();

  const handleSubmit = (komikId, vendor) => {
    const token = Cookies.get('token');
    if (!token) {
      return router.push('/signin');
    } else {
      router.push(`/checkout/${id}?komikId=${komikId}&vendor=${vendor}`);
    }
  };

  return (
    <>
      <Head>
        <title>Semina || Detail Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-navy">
        <Navbar />
      </section>

      <section className="stories">
        <div className="container">
          <div className="row">
            <div className="col-lg-6 col-12 mb-3 justify-content-center align-items-center">
              <img
                src={`${process.env.NEXT_PUBLIC_API}/${detailPage?.image?.nama}`}
                alt="semina"
                className="d-block"
                width="515"
              />
            </div>
            <div className="col-lg-6 col-12">
              <div className="d-flex flex-column">
                <div>
                  <div className="sub-title">
                    <span className="text-gradient-pink">Profile</span>
                  </div>
                  <div className="title">{detailPage.nama}</div>
                </div>
                <p className="paragraph">
                  Website ini didirikan dengan tujuan untuk mempercepat dan
                  mempermudah penikmat komik dalam membaca dan publikasi komik.
                  Tanpa perlu memikirkan biaya yang mahal, keterbatasan stok,
                  waktu pembelian, keterbatasan ruang penyimpanan, sulitnya
                  perawatan dan biaya produksi serta distribusi yang mahal.
                </p>
                <a href="#" className="btn-navy">
                  Read
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  const req = await getData(`api/v1/vendor/${context.params.id}`);

  const res = req.data;

  return {
    props: { detailPage: res, id: context.params.id },
  };
}
