import Head from 'next/head';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { getData } from '../utils/fetchData';
import React from 'react';
import CardKomikWithSearch from '../components/CardKomikWithSearch';


export default function Home({ dataKomik, dataGenre }) {
  return (
    <>
      <Head>
        <title>Semina || Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-navy">
        <Navbar />
      </header>
      <CardKomikWithSearch dataKomik={dataKomik} dataGenre={dataGenre} />
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  const reqKomik = await getData('api/v1/komik');
  const resKomik = reqKomik.data;

  const reqGenre = await getData('api/v1/genre');
  const resGenre = reqGenre.data;

  return {
    props: { dataKomik: resKomik, dataGenre: resGenre },
  };
}
