import Head from 'next/head';
import FormContact from '../components/FormContact';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';


export default function contact() {
  return (
    <>
      <Head>
        <title>Semina || Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-navy">
        <Navbar />
      </header>

      <FormContact />
      <Footer />
    </>
  );
}
