import Head from 'next/head';
import Brand from '../components/Brand';
import CardKomik from '../components/CardKomik';
import Footer from '../components/Footer';
import Header from '../components/Header';
import Statistics from '../components/Statistics';
import Stories from '../components/Stories';
import { getData } from '../utils/fetchData';

export default function Home({ data, dataUser }) {
  console.log(dataUser);
  return (
    <>
      <Head>
        <title>Semina || Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header dataUser={dataUser} />
      <Brand />
      <CardKomik data={data} title="Rekomendasi" subTitle="Browse" />
      <Stories />
      <Statistics />
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  const req = await getData('api/v1/komik');
  const res = req.data;

  const reqUser = await getData('api/v1/customer');
  const resUser = reqUser.data;

  return {
    props: { data: res, dataUser: resUser },
  };
}
