import Head from 'next/head';
import Brand from '../components/Brand';
import CardKomik from '../components/CardKomik';
import Footer from '../components/Footer';
import Header from '../components/Header';
import Statistics from '../components/Statistics';
import Stories from '../components/Stories';
import { getData } from '../utils/fetchData';

export default function HomePage({ data, dataKomikAction, dataKomikAdventure }) {
  return (
    <>
      <Head>
        <title>Semina || Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Brand />
      <CardKomik dataKomik={data} title="Komik Terbaik" subTitle="Jelajahi" />
      <CardKomik
        dataKomik={dataKomikAction}
        title="Aksi Terbaik"
        subTitle="Genre"
      />
      <CardKomik
        dataKomik={dataKomikAdventure}
        title="Petualangan Terbaik"
        subTitle="Genre"
      />
      <Stories />
      <Statistics />
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  const req = await getData('api/v1/komik-highest-rating');
  const res = req.data;

  const reqKomikAction = await getData('api/v1/komik-genre-action');
  const resKomikAction = reqKomikAction.data;

  const reqKomikAdventure = await getData('api/v1/komik-genre-adventure');
  const resKomikAdventure = reqKomikAdventure.data;

  return {
    props: {
      data: res,
      dataKomikAction: resKomikAction,
      dataKomikAdventure: resKomikAdventure,
    },
  };
}
