import Head from 'next/head';
import Navbar from '../components/Navbar';
import CardVendor from '../components/CardVendor';
import Footer from '../components/Footer';
import { getData } from '../utils/fetchData';
import SearchInput from '../components/SearchInput';
import Pagination from '../components/Pagination';
/* eslint-disable @next/next/no-img-element */
import React, { useState, useEffect } from 'react';
import { Col, Container, Row } from 'react-bootstrap';

export default function Home({ data }) {
  const [filteredKomikData, setFilteredKomikData] = useState(data);
  const [nameFilter, setNameFilter] = useState('');

  useEffect(() => {
    if (!nameFilter)
      setFilteredKomikData(data);
    if (nameFilter)
      setFilteredKomikData(
        data.filter((item) =>
          item.nama.toLowerCase().includes(nameFilter.toLowerCase())
        )
      );
    
  }, [nameFilter]);

  const handleChange = (e) => {
    setNameFilter(e.target.value);
  };

  return (
    <>
      <Head>
        <title>Semina || Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-navy">
        <Navbar />
      </header>
      <Container className="mt-5">
        <div className="row row-cols-lg-8 row-cols-md-1 row-cols-1 justify-content-lg-center">
          <Col>
            <SearchInput
              className="form-search"
              name="keyword"
              handleChange={handleChange}
            />
          </Col>
        </div>
      </Container>
      <CardVendor dataVendor={filteredKomikData} />
      {/* <Pagination pages={pages} handlePageClick={handlePageClick} /> */}
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  const req = await getData('api/v1/vendor');
  const res = req.data;

  return {
    props: { data: res },
  };
}
