import Head from 'next/head';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { getData } from '../utils/fetchData';
/* eslint-disable @next/next/no-img-element */
import React, { useState, useEffect } from 'react';
import CardVendorWithSearch from '../components/CardVendorWithSearch';

export default function Vendor({data}) {
  // const [data, setData] = useState([]);
  // useEffect(() => {
  //   const fetchData = async () => {
  //     try {
  //       const res = await getData('api/v1/vendor');

  //       setData(res.data);
  //     } catch (err) {}
  //   };

  //   fetchData();
  // }, []);

  // console.log('data');
  // console.log(data)

  return (
    <>
      <Head>
        <title>Semina || Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-navy">
        <Navbar />
      </header>
      <CardVendorWithSearch data={data} />
      
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  const req = await getData('api/v1/vendor');
  const res = req.data;

  return {
    props: { data: res },
  };
}
