/* eslint-disable @next/next/no-img-element */
import moment from 'moment';
import Head from 'next/head';
import Footer from '../../components/Footer';
import FormCheckout from '../../components/FormCheckout';
import Navbar from '../../components/Navbar';
import { getData } from '../../utils/fetchData';
import { formatDate } from '../../utils/formatDate';
import { useEffect } from 'react';

export default function Dashboard({ data }) {
  return (
    <>
      <Head>
        <title>Semina || Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-navy">
        <Navbar />
      </section>

      <section className="bg-navy">
        <div className="checkout container">
          <div className="text-center checkout-title">Invest In Yourself</div>
          {data.map((data) => (
            <div className="row row-cols-lg-8 row-cols-md-6 row-cols-lg-3 justify-content-lg-center mb-3">
              <div className="col-lg-1">
                <img
                  height={120}
                  width={100}
                  src={`${process.env.NEXT_PUBLIC_API}/${data?.komik?.image?.nama}`}
                  alt="semina"
                />
              </div>
              <div className="col-lg-7 col-md-5 col-sm-2">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item">{data.historyKomik.judul}</li>
                  <li class="list-group-item">{data.historyKomik.price}</li>
                  <li class="list-group-item">
                    {moment(data.date).format('HH.MM A')}
                  </li>
                </ul>
              </div>
            </div>
          ))}
        </div>
      </section>
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  const req = await getData(`/api/v1/transaksi`, {}, context.req.cookies.token);

  const res = req.data;

  return {
    props: { data: res },
  };
}
